-- Stacks Docs Database Initialization
-- Placeholder for any database-backed tooling.

-- Example (PostgreSQL):
-- CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
-- CREATE TABLE IF NOT EXISTS doc_events (
--   id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
--   file_path TEXT NOT NULL,
--   action TEXT NOT NULL,
--   payload JSONB,
--   created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
-- );